### ISSUE TITLE
Issues Running app on my machine

### ISSUE THREAD

**Issue by Lakhankumawat** [gdscnitp/Delrit#8]
```
Running Gradle task 'assembleDebug'...
Reading env from: .env
**************************
*** Missing .env file ****
**************************
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     F:\Ride-Sharing-App\build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:30: AAPT: error: resource string/MAPS_API_ANDROID (aka com.asmit.ride_sharing:string/MAPS_API_ANDROID) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
Exception: Gradle task assembleDebug failed with exit code 1
```

>build\app\intermediates\packaged_manifests\debug\AndroidManifest.xml:30
```
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="@string/MAPS_API_ANDROID" />
```
<hr>
<h3> Could you guys please tell me which api's you are using in this app so i can enable them on my end 
I would like contribute here </h3>
<p> Also please (if aware) mention the places where i need to change in android files after api keys </p>

**Comment by ViAsmit** [comment]
@Lakhankumawat 

Actually .env file contains some paid maps API Key, which are restricted for the time being... And hence I am not able to to share it right now. 

Even if I share it will not work because they are restricted with SHA.. ( can't leave them open, because they incur charges)

If you want to contribute... You can create a .env file, inside root folder with the following content:

MAPS_API_ANDROID=secret
MAPS_API_HTTPS=secret

You will be able to build and run the app, by adding this file only


Thank you

**Comment by Lakhankumawat** [comment]
firebase sha's are you taking about ?

**Comment by Lakhankumawat** [comment]
apart from these keys

MAPS_API_ANDROID=secret
MAPS_API_HTTPS=secret

i will look for these ,if just like any other keys if they are available on google console for free then i will be able to add o/w i don't have billing account even to get these keys for free trial so i might just leave it 🙂

**Comment by ViAsmit** [comment]
@Lakhankumawat 
you can get the Maps API key from gcloud, but you will only be able to render maps. Other functionalities are paid.
If you want to contribute, you may contribute on UI/UX part, or several other parts. I will be creating issues, once the examinations are over.

**Comment by Lakhankumawat** [comment]
> @Lakhankumawat you can get the Maps API key from gcloud, but you will only be able to render maps. Other functionalities are paid. If you want to contribute, you may contribute on UI/UX part, or several other parts. I will be creating issues, once the examinations are over.

great
